[project]
name = "pacopts"
version = "0.1.0"
description = "A simple script to list optional dependencies for pacman packages."
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["termcolor>=2.4.0"]

[project.license]
file = "LICENSE"

[project.scripts]
pacopts = "pacopts:main"
